spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/school}
    username: ${DB_USER:school}
    password: ${DB_PASS:school}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none          # KHÔNG create/update trong runtime
    open-in-view: false
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      schema-locations: file:./schema.sql
      # data-locations: classpath:data.sql, classpath:recompute.sql
      continue-on-error: true

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ca0f180e9518bb        # dán nguyên xi từ nút Copy
    password: 5b89a4644bba18  # dán nguyên xi từ nút Copy
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.trust: sandbox.smtp.mailtrap.io
      mail.debug: true

  app:
    mail:
      from: ${MAIL_FROM:no-reply@school.local}   # với Mailtrap có thể để tùy ý
      mock: false                                 # đảm bảo đang gửi thật qua Mailtrap  # nên trùng username
  security:
    jwt:
      secret: ${JWT_SECRET:change-me-in-env}
      access-minutes: 60
      refresh-days: 7

server:
  port: 8080
