spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/school}
    username: ${DB_USER:school}
    password: ${DB_PASS:school}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # lần đầu có thể dùng create-drop, xong rồi chuyển update
    open-in-view: false
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.format_sql: true
    sql:
      init:
        mode: never         # chỉ tạo schema nếu thiếu

server:
  port: 8080
