spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/school}
    username: ${DB_USER:school}
    password: ${DB_PASS:school}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none          # QUAN TRỌNG: không để create/update
    open-in-view: false
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.format_sql: true
    defer-datasource-initialization: true  # để data.sql chạy đúng thứ tự khi cần

  sql:
    init:
      mode: always                         # bật chạy schema.sql / data.sql
      schema-locations: file:./schema.sql
      #data-locations: classpath:data.sql, classpath:recompute.sql
      continue-on-error: true              # tùy chọn: không fail khi đã tồn tại

server:
  port: 8080
